### ISSUE TITLE
Add block support for Colophon

### ISSUE THREAD

**Issue by TremiDkhar** [a8cteam51/special-projects-blocks-monorepo#28]
### Description

Custom block that will render the [Colophon](https://github.com/a8cteam51/colophon) in both the editor as well as the frontend.

**Comment by tommusrhodus** [comment]
This won't live in the monorepo, but will instead live in the Colophon repo.

It looks like @georgestephanis requested changes here: https://github.com/a8cteam51/colophon/pull/29

Will close this one.
